In [1]:
import numpy as np
import matplotlib.pyplot as plt
def gauss_seidel(A, b, x0=None, tol=1e-10, max_iter=1000):
    """
    Résout le système d'équations linéaires A * x = b en utilisant la méthode de Gauss-Seidel.
    
    Paramètres:
    ----------
    A : array_like
        Matrice de coefficients (n x n) du système.
    b : array_like
        Vecteur des termes indépendants (n).
    x0 : array_like, optional
        Approximation initiale (vecteur de zéros par défaut).
    tol : float, optional
        Tolérance pour l'erreur relative (1e-10 par défaut).
    max_iter : int, optional
        Nombre maximal d'itérations (1000 par défaut).
    
    Retourne:
    -------
    x : ndarray
        Vecteur solution.
    num_iter : int
        Nombre d'itérations effectuées.
    
    Lève:
    -----
    ValueError
        Si les dimensions de A et b sont incompatibles.
    RuntimeWarning
        Si la matrice n'est pas à diagonale dominante.
    """
    # Vérification des entrées
    A = np.asarray(A, dtype=np.float64)
    b = np.asarray(b, dtype=np.float64)
    
    n = len(b)
    
    if A.shape != (n, n):
        raise ValueError("Dimensions incompatibles : A doit être carrée (n x n) et b de taille n")
    
    # Vérification de la diagonale dominante (optionnelle mais recommandée)
    if not np.all(np.abs(A.diagonal()) >= np.sum(np.abs(A), axis=1) - np.abs(A.diagonal())):
        import warnings
        warnings.warn("La matrice n'est pas à diagonale dominante strictement - la convergence n'est pas garantie",
                     RuntimeWarning)
    
    # Initialisation
    if x0 is None:
        x = np.zeros(n)
    else:
        x = np.asarray(x0, dtype=np.float64).copy()
        if len(x) != n:
            raise ValueError("La taille de x0 ne correspond pas à la dimension du système")
    
    # Itérations de Gauss-Seidel
    for k in range(max_iter):
        x_prev = x.copy()
        
        for i in range(n):
            sigma = np.dot(A[i, :i], x[:i]) + np.dot(A[i, i+1:], x_prev[i+1:])
            x[i] = (b[i] - sigma) / A[i, i]
        
        # Critère d'arrêt
        error = np.linalg.norm(x - x_prev, ord=np.inf)
        if error < tol * np.linalg.norm(x, ord=np.inf):
            return x, k + 1
    
    # Si on arrive ici, la convergence n'a pas été atteinte
    print(f"Attention : Convergence non atteinte en {max_iter} itérations (erreur = {error:.2e})")
    return x, max_iter


def main():
    """Exemple d'utilisation avec des tests de validation."""
    # Système test avec solution connue x = [1, 1, 1]
    A = np.array([[4, 1, -1],
                  [1, 5, -1],
                  [1, -1, 6]], dtype=float)
    b = np.array([5, 6, 7], dtype=float)
    
    print("Matrice A :\n", A)
    print("Vecteur b :", b)
    
    # Résolution
    solution, iterations = gauss_seidel(A, b)
    
    print("\nRésultats :")
    print(f"Solution : {solution}")
    print(f"Itérations : {iterations}")
    print(f"Vérification A@x : {np.dot(A, solution)}")
    print(f"Erreur résiduelle : {np.linalg.norm(np.dot(A, solution) - b):.2e}")


if __name__ == "__main__":
    main()

Matrice A :
 [[ 4.  1. -1.]
 [ 1.  5. -1.]
 [ 1. -1.  6.]]
Vecteur b : [5. 6. 7.]

Résultats :
Solution : [1.24347826 1.1826087  1.15652174]
Itérations : 12
Vérification A@x : [5. 6. 7.]
Erreur résiduelle : 3.05e-11
